# Generated by Django 3.1.5 on 2022-01-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, null=True)),
                ('aadhar', models.IntegerField()),
                ('pan', models.IntegerField()),
                ('address', models.CharField(blank=True, max_length=350)),
                ('profile', models.ImageField(blank=True, default='upload/main/img/profile_default.jpg', upload_to='upload/main/img/')),
            ],
        ),
    ]
